name: Build and test React

on:
  push:
    branches: [ "website" ]
  pull_request:
    branches: [ "website" ]
    
jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-versions: [16.x]

    env:
      CI: false

    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Cache dependencies ⛓
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}
          
      - name: Install dependencies ⛓
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci --ignore-scripts
        
      - name: Build 🔨
        run: npm run build --if-present
        
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
